"""Yıllar arasında tekrar eden soru kalıpları (insights_gm.json → tekrar)."""
T = [
 ("Fikri ve sınai haklarda alıkoyma süreleri ve yasak işlemler", "GM_FSMH",
  {2021: [12, 17], 2022: [27, 38], 2023: [56], 2024: [31], 2025: [28]},
  "Re'sen alıkoyma 3 iş günü; hak sahibi ihtiyati tedbiri 10 iş gününde (çabuk bozulan eşyada 3) getirir; başvuru en fazla 1 yıl için yapılır; durdurulan eşya TGB'yi terk edemez, serbest bölgeye konamaz."),
 ("Incoterms 2020: kurallar ve taşıma türleri", "GM_INCOTERMS",
  {2021: [67], 2022: [29, 65], 2023: [65, 71], 2024: [1], 2025: [11]},
  "EXW, FCA, CPT, CIP, DAP, DPU ve DDP tüm taşıma türlerine; FAS, FOB, CFR ve CIF yalnız deniz ve iç su yoluna uygundur. Kuralları ICC hazırlar; DPU, DAT'ın yerini almıştır."),
 ("Geri gelen eşya muafiyeti: süre, başlangıç, istisnalar", "GM_MUAFIYET",
  {2021: [22, 24, 76], 2022: [69], 2023: [27], 2024: [61, 69, 70]},
  "Süre 3 yıldır ve fiili ihraç tarihinden başlar (deniz yolunda geminin hareketi, kara yolunda sınırdan fiilen çıkış). İhracı dış ticaret önlemine konu eşya muafiyetten yararlanamaz."),
 ("Kullanılmış taşıtın gümrük kıymeti (amortisman)", "GM_KIYMET",
  {2022: [91], 2023: [84], 2024: [22], 2025: [16]},
  "Fatura bedelinden kullanım süresi için amortisman düşülür: ilk yıl %20, sonraki yıllar %10, toplamda en çok %80. Sayımın model yılından mı fatura yılından mı başlayacağı anahtarlarda farklı ele alınmış; bu soru tipi itiraza en açık hesaplardandır."),
 ("Antrepo götürü teminatı", "GM_ANTREPO",
  {2022: [41, 68], 2023: [99], 2024: [83, 84], 2025: [82]},
  "Götürü teminatı antrepo işleticisi verir; tutar alan ya da tank kapasitesi kademelerine göre hesaplanır, 40.000.000 TL'yi aşan kısım dikkate alınmaz. Tank ilavesinde yalnızca ilave edilen kısım esas alınır; işlemleri bölge müdürlüğü sonuçlandırır."),
 ("Royalti ve lisans ücretinin kıymete eklenmesi", "GM_KIYMET",
  {2021: [83, 84], 2022: [92, 98], 2024: [13, 15, 23], 2025: [14, 17]},
  "Satış şartı olan ve ithal eşyasıyla ilgili royalti kıymete eklenir; Türkiye'de çoğaltma hakkı bedeli eklenmez. Ödemenin ithalattan önce ya da sonra yapılması sonucu değiştirmez; 3 yıllık zamanaşımı ayrıca kontrol edilir."),
 ("İşlenmemiş kıymetli maden ithalatı (32 sayılı Karar)", "GM_KAMBIYO",
  {2022: [1], 2023: [50, 51], 2024: [5], 2025: [31, 37]},
  "İşlenmemiş standart ve standart dışı kıymetli madeni yalnızca TCMB ile kıymetli madenler aracı kuruluşları ithal edebilir. Serbest bölgeye getirilmesi yasak değildir; kıymetli maden ihracı serbesttir."),
 ("TIR karnesi ve TIR Sözleşmesi", "GM_TRANSIT",
  {2022: [46], 2023: [93], 2024: [77, 78, 79], 2025: [71, 72]},
  "Her taşıt veya konteyner için ayrı karne esastır. Alkol ve tütün ancak özel ibareli karneyle taşınır; geçerliliğinin son günü hareket gümrüğüne ibraz edilen karne kabul edilir."),
 ("Transit teminatı, kefil ve GRN", "GM_TRANSIT",
  {2021: [74], 2022: [51, 61, 66], 2024: [74, 75], 2025: [65]},
  "Kefil, Türkiye'de yerleşik, rejim hak sahibinden farklı bir banka veya finans kuruluşudur. Teminat mektubu, beyannameler kapanıp GRN kapatıldıktan 10 ay sonra iade edilir; kara yolu dışındaki taşımalarda kural olarak teminat aranmaz."),
 ("Transit basitleştirmeleri ve izin sahibinin yükümlülükleri", "GM_TRANSIT",
  {2022: [63], 2023: [87, 92], 2024: [76], 2025: [66, 70]},
  "Demiryolu basitleştirmesinde CIM bilgileri iletilir. İzin sahibi manifestolara 3 yıl erişim sağlar ve havalimanı değişikliğini 15 gün önce bildirir; başvuruda finansal büyüklük kriter değildir."),
 ("Anlaşmalara göre menşe ispat belgesi eşleştirmesi", "GM_TERCIHLI_STA",
  {2023: [47], 2024: [32, 35, 41], 2025: [33, 34, 36]},
  "İran TTA'da İran menşe ispat belgesi, Azerbaycan TTA'da TR-AZ Menşe İspat Belgesi, Singapur STA'da menşe beyanı, Özbekistan TTA'da EUR.1 kullanılır; Form A yalnız GTS'de geçerlidir. AB ile sanayi ürünleri ve işlenmiş tarım ürünleri ticaretinde A.TR kullanılır."),
 ("Anlaşma tarafı ülkeler (STA, TTA, TPS-OIC, EFTA)", "GM_TERCIHLI_STA",
  {2022: [23], 2023: [100], 2024: [36, 40], 2025: [26, 97]},
  "İran, Azerbaycan, Özbekistan ve Pakistan ile STA değil tercihli ticaret anlaşması vardır; Uruguay ile STA yoktur. EFTA: İsviçre, Norveç, İzlanda, Lihtenştayn."),
 ("Gümrükçe vize edilen ve edilmeyen menşe belgeleri", "GM_TERCIHLI_STA",
  {2022: [9], 2023: [54], 2024: [33]},
  "EUR.1 ve A.TR gümrükçe vize edilir. Menşe şahadetnamesini odalar onaylar, Form A'yı lehdar ülke makamları düzenler; fatura beyanı ve menşe beyanı vize gerektirmez."),
 ("ÖTV (IV) sayılı liste kapsamı", "GM_OTV",
  {2023: [60], 2024: [16], 2025: [8, 9]},
  "Parfüm, kozmetik, saç spreyi, havyar ve tırnak makası (IV) sayılı listededir; sade gazoz ve çerçeveli cam ayna değildir. Diplomatik istisna (IV) sayılı listeyi kapsamaz."),
 ("KKDF kesintisi yapılan ve yapılmayan ithalat", "GM_FONLAR",
  {2021: [87], 2022: [2, 5], 2023: [52], 2024: [14]},
  "Mal mukabili, kabul kredili ve vadeli akreditifli ithalatta KKDF kesilir. Borsa İstanbul'a gelen standart kıymetli madende ve süresinden önce ödenen istisnai kıymet bedelinde kesinti yapılmaz."),
 ("Konsinye ihracat", "GM_DIS_TIC_IHRACAT",
  {2022: [10, 45], 2024: [63, 72], 2025: [60]},
  "Başvuru İhracatçı Birlikleri Genel Sekreterliğine yapılır; kesin satış ihraçtan itibaren 1 yıl içinde gerçekleşmelidir ve haklı nedenle 2 yıl uzatılabilir."),
 ("İhracı yasak ve ön izne bağlı mallar (96/31)", "GM_DIS_TIC_IHRACAT",
  {2021: [54], 2022: [35], 2025: [61]},
  "Tütün tohumu ve sultani çekirdeksiz asma fidanının ihracı yasaktır; afyon ve haşhaş kellesi ön izne bağlıdır."),
 ("Özet beyan ve geçici depolama yeri şartları", "GM_GIRIS_BEYAN",
  {2021: [7, 30, 35, 36], 2022: [58, 59], 2023: [96]},
  "Geçici depolama yeri açma başvurularını bölge müdürlüğü sonuçlandırır. Çıkış özet beyanından sonra eşya 150 gün içinde çıkmazsa beyan verilmemiş sayılır; muayene bildiriminden sonra özet beyan değiştirilemez."),
 ("Gümrük müşavirliği asgari ücret tarifesi", "GM_MESLEK",
  {2022: [56], 2024: [100], 2025: [99]},
  "Aynı beyannamede birden fazla rejim varsa yüksek ücret uygulanır. Sektörel dış ticaret şirketlerinde beyanname sayısına göre %35 veya %50 indirim yapılabilir; tutar soruları her yılın tebliğinden gelir."),
 ("Telafi edici vergi ve geri ödeme sistemi", "GM_DIR",
  {2021: [14], 2022: [42], 2024: [67], 2025: [63]},
  "TEV bir ithalat vergisidir ve ihracat beyannamesinin tescilinde doğar. Miktar kısıtlaması, kota veya lisans söz konusu olduğunda geri ödeme sistemi uygulanmaz."),
 ("Sınır ticaret merkezleri ve sınır ticareti", "GM_YATIRIM_SINIR",
  {2021: [75], 2022: [30], 2023: [31]},
  "Sınır ticaret merkezleri gümrük işlemlerinde TGB dışında sayılır. Altyapı, güvenlik ve işletme valiliğin görevidir; uygunluk belgesi her ürün için ayrı düzenlenir ve devredilemez."),
 ("YGM tespit işlemi kodları", "GM_YGM",
  {2021: [31], 2025: [98, 100]},
  "AN kodları antrepo, DR kodları DİR tespitleridir. Genel antrepolarda AN7, AN8 ve AN9 tespitlerini aynı YGM yapmalıdır."),
 ("İhrakiye, kumanya ve tamamlayıcı beyan", "GM_OZEL_TASIT",
  {2021: [25, 26], 2023: [25, 26, 30]},
  "Gemiyle ihracatta fiili ihraç tarihi geminin hareket tarihi, ihrakiyede teslim tarihidir. Basitleştirilmiş usulle yapılan teslimlerde tamamlayıcı beyan, izleyen ayın ilk 7 iş gününde verilir."),
 ("Kaçak akaryakıtta numune ve tasfiye", "GM_KACAKCILIK",
  {2021: [41, 47], 2024: [88]},
  "Teknik düzenlemeye uygun olmayan kaçak akaryakıt il özel idaresi veya yatırım izleme ve koordinasyon başkanlığınca en yakın rafineriye satılır. Numuneleri gümrük idaresi saklar."),
 ("Isıtma tertibatlı ön cam: taşıt aksamı", "GM_TARIFE_SINIF",
  {2023: [6], 2025: [47]},
  "Isıtmalı ön cam 70.07'de değil, taşıt aksamı olarak sınıflandırılır: lokomotifte 86.07, otomobilde 8708.22."),
 ("64.06 ayakkabı aksamı ve 64. fasıl notları", "GM_TARIFE_SINIF",
  {2022: [85], 2024: [48, 58], 2025: [41, 44]},
  "Bağcık, kopça, toka ve süs eşyası 64.06 anlamında aksam sayılmaz; ortopedik ayakkabı 90.21'dedir. 64. fasıl XII. Bölümdedir."),
 ("Memeliler ve yenilebilir böcekler (HS 2022)", "GM_TARIFE_SINIF",
  {2022: [79, 83], 2024: [2], 2025: [39]},
  "Balina ve yunus memelidir; canlı halde 01.06'da yer alır, 3. fasılda değil. HS 2022 ile insan tüketimine uygun böcekler 04.10'a alınmıştır."),
 ("Elektronik sigara ve 24.04", "GM_TARIFE_SINIF",
  {2022: [86], 2025: [52]},
  "Yanmadan solunan tütün ve nikotin ürünleri 24.04'te, elektronik sigara cihazı 85.43'te sınıflandırılır."),
 ("1/95 OKK md. 28 ve Gümrük Kıymeti Komitesi", "GM_ULUSLARARASI_TIC",
  {2023: [61, 85], 2024: [11], 2025: [2]},
  "1/95 OKK md. 28 menşe, kıymet, beyan ve serbest dolaşım gibi uyum alanlarını sayar. Gümrük Kıymeti Komitesi DTÖ'de, Teknik Komite ise DGÖ'dedir."),
]

def tekrar():
    out = []
    for kalip, konu, s, bilgi in T:
        out.append(dict(kalip=kalip, konu=konu, sorular={str(k): v for k, v in s.items()}, bilgi=bilgi))
    out.sort(key=lambda t: (-len(t["sorular"]), -sum(len(v) for v in t["sorular"].values())))
    return out
